"""Seal a bounded whole-aircraft study without turning failed gates into claims."""
import argparse,json,sys
import numpy as np
from run_aircraft_a05 import ROOT,OUT,CFG,read,dump,sha,rel,now,harness,preserved
REPORT=OUT/'rapport_aircraft_a05.md'
HANDOFF=ROOT/'harness/handoffs/WTC1_AIRCRAFT_A05_HANDOFF.md'
NEXT=('AIRCRAFT-A06 : poursuivre l’avion entier en traitant le radôme au-delà de sa limite élastique, avec endommagement/rupture et énergie explicites issus de références indépendantes ou de plages annoncées. Vérifier un mécanisme simple avant transfert dans un nouveau départ intact ; examiner simultanément sensibilité spatiale/contact et amortissement natif métallique dm/dn. Ne pas ajuster résistances, énergie, maillage ou érosion à des dégâts NIST. Ne pas prolonger A05 comme impact physique qualifié. Garder la modélisation géométrique/contact des moteurs comme domaine encore manquant ; préserver V11F et V11S différée.')

def prepare():
    assert not REPORT.exists() and not HANDOFF.exists();s=read(OUT/'cached_review/review.json');assert s['integrity_only_pass'];assert read(OUT/'saved_tensor_and_geometry_review.json')['pass'];n=preserved();cfg=read(CFG);paths={k:OUT/v for k,v in read(OUT/'case_selection.json')['case_directories'].items()};nom=next(r for r in s['cases'] if r['case']['id']=='COMP_SELF');metal=s['cases'][0];fine=s['cases'][-1];g=read(paths['COMP_SELF']/'generation.json');gf=read(paths['COMP_FINE']/'generation.json');mesh=read(paths['COMP_FINE']/'mesh.json');half,spatial=s['comparisons'];execs=[read(p) for p in OUT.rglob('*.execution.json')];main=[r for r in execs if r['exe'].endswith('engine_win64.exe') and r['args'][1].endswith('_0001.rad')];obs=[r for r in execs if r['exe'].endswith('engine_win64.exe') and r['args'][1].endswith('_0002.rad')];starters=[r for r in execs if r['exe'].endswith('starter_win64.exe')];assert len(main)==9 and len(obs)==9 and len(starters)==12
    for row in read(OUT/'source_manifest.json')['local_inputs']:assert sha(ROOT/row['path'])==row['sha256']
    for r in s['cases']:
        d=paths[r['case']['id']];z=np.load(d/'verified_states_SI.npz');assert all(np.all(np.isfinite(z[k])) for k in z.files);assert r['requested_horizon_reached'];assert read(d/'observer_preservation.json')['main_outputs_unchanged']
        if r['case']['self_contact']:assert read(d/'history_recovery.json')['pass']
    review={'created_utc':now(),'pass':True,'integrity_only':True,'old_files_preserved':n,'main_solver_jobs':len(main),'observation_jobs':len(obs),'starter_jobs':len(starters),'old_solver_reruns':0,'main_wall_seconds_sum':sum(r['seconds'] for r in main),'main_timeboxes_reached':sum(r['exit_code']=='TIMEOUT' for r in main),'native_converter_crashes_preserved':6,'python_version':sys.version,'numpy_version':np.__version__,'harness':harness(),'all_declared_checks_pass':False,'physical_impact_qualified':False};dump(OUT/'saved_result_review.json',review)
    table='\n'.join(f"| {r['case']['id']} | {r['actual_main_end_time_ms']:.7f} | {r['final_contact_impulse_Ns'][0]:.3f} | {r['final_global_plastic_work_J']/1000:.3f} | {r['final_generated_energy_J']/1000:.3f} | {r['final_energy_residual_J']/1000:.3f} | {r['maximum_face_reference_strength_ratio']:.3f} |" for r in s['cases'])
    failures='\n'.join('- **'+r['case']['id']+'** : '+(', '.join(r['failed_checks']) or 'aucun échec dans les critères déclarés')+'.' for r in s['cases'])
    src=cfg['sources'];st=g['laminate_reference'];nm=read(paths['COMP_SELF']/'mesh.json')
    REPORT.write_text(f'''# AIRCRAFT-A05 — nez arrondi et sandwich composite dans l’avion entier

Le substitut plat métallique du nez a été remplacé par une surface arrondie, puis par un sandwich élastique de référence dans des départs intacts de l’avion entier. **Les huit cas avec contact atteignent 2 ms ; le contrôle libre atteint 0,6 ms.** Le blocage géométrique d’A04 à environ 1,63 ms n’apparaît pas dans ces essais. Cela constitue un progrès de modélisation, pas une reconstruction qualifiée de l’impact.

Le contrôle libre et les vérifications de masse, graphe, appuis, états finis et quantité de mouvement passent. La réduction du pas passe, mais **l’affinement du nez donne 14,35 % d’écart d’impulsion et 43,25 % d’énergie générée : les deux critères spatiaux échouent**. Les résistances de référence des faces sont dépassées dans tous les contacts composites. Tous les contacts échouent le bilan énergétique local. Aucun matériau n’est renforcé pour cacher ces résultats ; aucun dégât NIST ne sert de cible.

## 1. Faits directement observés ou transcrits

La fiche [Boeing ARFF 767, page PDF 6]({src[0]}) place le radôme parmi les composants composites. Sa date 2022 et l’absence de stratification interdisent de l’attribuer précisément à AA11 en 2001. La fiche [HexPly 913, page 4]({src[1]}) donne pour 7781GL/R913 37 %, 300 AW une densité de 1,83 g/cm³, E en traction 22 GPa, résistance en traction 450 MPa et compression 460 MPa ; E en compression est 28 GPa. Ce sont des valeurs typiques à température ambiante, pas des mesures de radôme 767. Le cisaillement court de 65 MPa n’est pas une résistance de cisaillement dans le plan.

La fiche [HRH-10, page 4, code HRH-10-3.2-48]({src[2]}) donne une densité nominale 48 kg/m³, E transversal 138 MPa, G longitudinal 41 MPa et transversal 24 MPa, résistances de cisaillement 1,21/0,69 MPa et compression nue 2,07 MPa. Elle ne prouve pas que cette âme équipe le radôme du 767. Les deux nouveaux PDF sont acquis, hashés et conservés en lecture seule. Ils sont exclus de la redistribution de nos propres calculs ; URLs et script de réacquisition sont conservés.

Les neuf Starter retenus ont zéro erreur et avertissement ; les neuf Engines et neuf observateurs terminent normalement. 12 Starter au total incluent trois tentatives de format rejetées avant Engine. Aucun ancien solveur n’a été relancé. Le calcul principal totalise {review['main_wall_seconds_sum']:.2f} s, chaque cas étant plafonné à 300 s. Les états natifs et leurs connectivités sont vérifiés par identifiants ; les cellules virtuelles RBE3 d’identifiant élément 0 sont exclues de la collecte des tenseurs physiques.

## 2. Résultats d’un modèle officiel

Aucun résultat officiel nouveau n’est utilisé comme objectif. La façade de 59 colonnes × 3 étages, 31 792 nœuds et 31 986 quadrilatères conserve les entrées nominales NIST héritées et leurs limites représentatives. Cette dépendance aux dimensions nominales demeure déclarée. Aucun motif de destruction NIST, aucune durée d’effondrement ni résultat historique ne règle le composite, le contact ou la géométrie. Les résultats ci-dessous sont ceux de notre modèle exploratoire OpenRadioss.

## 3. Affirmations des archives locales

Aucune archive n’est rescannée et aucune vidéo n’est analysée. Les {n} fichiers antérieurs épinglés sont préservés. Les échecs A02 de CG, les extrapolations A03, les arrêts et premières interprétations A04 restent visibles. L’annotation A04 du triangle 4050 utilisait des indices de tableau commençant à zéro ; ses vrais identifiants natifs sont **2041, 18, 19**. Le deck A04 n’est pas modifié. V11F froid, V11R et V11S différée, I02I-M différée restent conservés.

## 4. Hypothèses, unités et historique

La zone modifiée couvre le nez jusqu’à X=2 m. Sa section ellipsoïdale propre au modèle suit r(x)/r(2m)=√[1−(1−x/2m)²]. La première couronne passe de X=0 à 0,25 m ; la pointe reste à X=0 et la jonction à 2 m utilise les nœuds communs. Dimensions, jonction et épaisseurs sont des hypothèses, pas une reconstruction de fabrication. Hors de cette zone, les coordonnées restent identiques à 10⁻⁷ mm près ; la recomposition trigonométrique de la couronne de jonction laisse seulement un arrondi maximal de 4,15×10⁻⁸ mm. Les cartes de façade, masses additionnelles, appuis et vitesse ne changent pas.

ROUND_METAL conserve les poutres et les lois métalliques A04 en ne changeant que la forme du nez et les orientations géométriques nécessaires. Sa masse varie naturellement de +48,768 kg. Les cas composites retirent {len(g['removed_beams'])} cadres/longerons fictifs situés dans les deux premiers mètres et remplacent 216 triangles de peau/cap par le sandwich. La variante fine utilise {gf['radome_elements']} triangles de nez, {mesh['aircraft_node_count']} nœuds avion et {len(mesh['nodes_mm'])} nœuds au total ; elle subdivise exactement les mêmes facettes planes, sans changer leur surface ni la masse. La frontière de 24 arêtes est conforme et partagée avec le fuselage, sans nœud suspendu. Cette jonction est parfaitement liée ; sa rupture n’est pas calculée.

| Couche de référence | Épaisseur nominale (mm) | ρ (kg/m³) | E1/E2 (MPa) | ν12 | G12/G23/G31 (MPa) |
|---|---:|---:|---:|---:|---:|
| Face verre/époxy | 0,5 chacune | 1830 | 22000/22000 | 0,25 | 4000/4000/4000 |
| Âme aramide nid d’abeille | 8 | 48 | 1/1 | 0,1 | 0,5/24/41 |

Seuls ρ et E1 de la face, ρ et les modules transversaux de l’âme sont repris des fiches. E2, ν, les G de face et E1/E2/G12 de l’âme sont des approximations annoncées. E33 vaut 10000/138 MPa dans les cartes mais n’est pas une compression normale résolue par ces coques en contrainte plane. La rigidité de compression/écrasement réel du nid d’abeille et le délaminage restent absents.

Le sandwich emploie [TYPE51]({src[4]}) avec trois [TYPE19]({src[5]}) de trois points Gauss chacun. Les listings natifs confirment trois points par couche, donc neuf dans l’épaisseur. Axe de référence : X global projeté dans le plan, maintenu en co-rotation. Les sous-triangles coplanaires conservent cette direction initiale. [LAW25 Iform=0]({src[3]}) est maintenue élastique avec limite numérique 10¹² MPa et déformations numériques de défaillance 10³⁰. Ces nombres ne représentent pas une résistance réelle. Les valeurs physiques de référence 450/460 MPa sont des diagnostics séparés. Ni rupture, ni érosion, ni rate law, ni effet thermique ne sont activés. Les matériaux métalliques restent A04 élastoplastiques parfaits, E=73,1/71,7/200 GPa, a=324/503/427,656 MPa ; aucune variante H=0,02E n’est sélectionnée.

Pour le sandwich nominal, masse surfacique **{st['areal_mass_kg_m2']:.3f} kg/m²**, surface {g['radome_area_m2']:.9f} m², masse de radôme {st['areal_mass_kg_m2']*g['radome_area_m2']:.6f} kg. Matrices de référence : A11=A22={st['A_N_mm'][0][0]:.6f} N/mm, A12={st['A_N_mm'][0][1]:.6f}, A66={st['A_N_mm'][2][2]:.6f} ; B=0 par symétrie ; D11=D22={st['D_Nmm'][0][0]:.6f} N·mm, D12={st['D_Nmm'][0][1]:.6f}, D66={st['D_Nmm'][2][2]:.6f}. L’intégrale analytique de Q, zQ et z²Q concorde avec la quadrature à {st['quadrature_relative_error']:.3g} près. Ce contrôle vérifie l’intégration de référence, pas une identification expérimentale de rigidité ni à lui seul la flexion native du nez.

L’avion composite nominal pèse {g['mass_kg_aircraft']:.6f} kg, soit −196,325 kg par rapport à A04. Faces 0,25/1 mm : 121945,890303/121996,801402 kg. Aucune réserve de masse ne compense cette modification ; les 53,187 t de vide non résolu restent sans raideur cachée. Les moteurs restent deux masses de 4500 kg et leurs attaches, sans surfaces de contact. Carburant et charge hérités : 30/10 t. La façade conserve 69310,977272 kg.

Conditions propres au test : v0=(-200,5,2) m/s, attitude nulle, distance initiale pointe-plan de façade 50 mm, sans trajectoire imposée après t=0. Pas de gravité, précharge, noyau, planchers ou coins. Appuis haut/bas : 944 nœuds fixes. Unités natives g/mm/ms/MPa/N/N·mm ; conversions vers SI : g×10⁻³, mm×10⁻³, ms×10⁻³, N·mm×10⁻³ J, N·ms×10⁻³ N·s. mm/ms=m/s ; déformations sans dimension. Seed1102030, aucun tirage.

Contact externe TYPE7 : gap constant 5 mm ; variante gap selon épaisseurs avec Igap=1 et Gapmin=1 mm. Autocontact limité au radôme seul : gap égal à 8,5/9/10 mm selon épaisseur. Friction nulle, viscosité normale 10⁻²⁰, pas de correction initiale imposée ni mass scaling. Aucun contact global du reste de l’avion ou entre arêtes n’est qualifié.

## 5. Résultats dérivés, réactions et bilans

| Cas | Fin observée (ms) | Jx contact (N·s) | PW (kJ) | Énergie générée (kJ) | Résidu (kJ) | Diagnostic face max |
|---|---:|---:|---:|---:|---:|---:|
{table}

Le premier contact nominal est enregistré à {nom['contact_onset_history_ms']:.7f} ms ; gap selon épaisseurs à 0,2204836 ms. Cadence d’histoire 0,02 ms et d’animation 0,2 ms : ces valeurs ne sont pas des instants exacts de premier contact ou de résistance atteinte. La face nominale dépasse sa référence au premier état de {nom['first_saved_face_reference_exceeded_ms']:.6f} ms ; diagnostic maximal {nom['maximum_face_reference_strength_ratio']:.3f}. Celui-ci utilise les valeurs propres du tenseur de contrainte dans le plan, divisées par 450 MPa en traction et 460 MPa en compression, sous l’hypothèse propre de résistances normales identiques dans les directions du tissu. Ce n’est ni un indice Tsai-Wu identifié, ni une probabilité, ni une fracture calculée. Contraintes natives aux points extrêmes des plis ; déformations natives extrapolées suivant [ANIM/SHELL/TENS]({src[7]}). Les tenseurs signés restent dans composite_signed_tensors.npz ; leur base est élémentaire, pas directement celle de l’orthotropie. Aucun seuil de cisaillement/crush de l’âme n’est déclaré validé par ces sorties.

ROUND_METAL atteint εp coque0,195964 et εp maximale des 696 poutres suivies0,09521 ; le diagnostic de coque≤0,1 échoue. Dans COMP_SELF, εp max coque0,011739 et travail plastique global {nom['final_global_plastic_work_J']/1000:.6f} kJ : ce travail provient des métaux. Le radôme élastique garde εp=0, même au-delà de sa résistance de référence ; cela ne signifie pas qu’il resterait intact. Les 504 poutres suivies dans les cas composites restent une sélection max(Xextrémités)≤8 m, avec ordre natif F1,F2,F3,M1,M2,M3,IE,SX,EPSP ; SX ne qualifie pas les fibres de flexion.

Réduire le facteur de pas 0,8→0,4 à l’instant commun {half['common_time_ms']:.8f} ms donne {half['impulse_relative_difference']*100:.5f} % d’écart vectoriel d’impulsion et {half['generated_energy_relative_difference']*100:.5f} % d’énergie générée ; seuils5/10 % passent. Affiner seulement le maillage du nez à l’instant commun {spatial['common_time_ms']:.8f} ms donne {spatial['impulse_relative_difference']*100:.5f}/{spatial['generated_energy_relative_difference']*100:.5f} % ; seuils10/10 % échouent. Deux maillages ne permettent pas d’extrapolation convergée ni de choisir celui qui ressemble à un dommage observé. Leur masse diffère de {s['fine_mass_difference_kg']:.3g} kg et leur surface de {s['fine_area_difference_m2']:.3g} m², donc l’écart n’est pas dû à un réajustement global de masse ou de géométrie.

L’autocontact reste inactif : toutes ses colonnes d’impulsion sont nulles, les déplacements sauvés avec/sans autocontact sont bit à bit identiques. Cette fenêtre ne valide pas son fonctionnement après pliage actif. Les différences de quelques centaines de joules à la fin avec/sans autocontact proviennent de précision CSV/relecture float32, inférieures à l’allocation déclarée1000 J, pas d’une dissipation physique d’autocontact.

Le contact externe brut est à nouveau compatible avec une **impulsion cumulée N·ms**, J=0,001(raw−raw0), pas avec une force à intégrer une deuxième fois. Les bilans Pfaçade−Pfaçade0=J+Jappui et Pglobal−Pglobal0=Jappui passent la tolérance10 N·s+2 %|J|. Les appuis fixes ne travaillent pas. Leurs petites colonnes sont conservées sous les deux interprétations impulsion cumulative/force intégrée ; leurs unités ne sont pas indépendamment distinguées face à l’arrondi du mouvement global. Pavion=Pglobal−Pfaçade inclut les masses additionnelles.

Énergie comptée = Ktranslation+Krotation+Uinterne+hourglass+ressorts+contactélastique+friction+dissipationcontact. Résidu = ΔEcomptée−Wextérieur. **PW est inclus dans Uinterne**, vérifié sur toutes les histoires et jamais ajouté deux fois. CONTACT ENERGY n’est pas ajoutée à ses composantes. L’énergie générée est rotation+interne+hourglass+ressorts+contactélastique. Aucune énergie perdue n’est réinjectée. K0 nominal={nom['initial_KE_J']/1e9:.9f} GJ, résidu terminal={nom['final_energy_residual_J']/1000:.3f} kJ, soit {abs(nom['final_energy_residual_J'])/nom['final_generated_energy_J']*100:.2f} % des {nom['final_generated_energy_J']/1000:.3f} kJ générés. Tous les contacts passent le critère global0,5 %K0 mais échouent le critère local5 %gen+1000 J après1kJ généré. Un petit résidu relatif au vol entier ne clôt pas le bilan local du nez. Les comparaisons A04 se fondent exclusivement sur ses NPZ sauvegardés, sans ancien Engine.

## 6. Contradictions, informations manquantes et critères échoués

{failures}

La construction exacte du radôme, sa courbe dynamique, les interfaces, l’écrasement normal de l’âme et la rupture ne sont pas identifiés. La loi élastique est extrapolée après dépassement de résistance ; sa poursuite jusqu’à2ms est un résultat numérique de sensibilité, pas l’impact physique. La sensibilité spatiale et le bilan local sont ouverts. Assemblages et sections du fuselage restent hypothétiques ; moteurs sans contact, rupture métallique, carburant fragmenté, incendie et interaction avec noyau/planchers demeurent absents. L’écart VONM moyen/points extrêmes d’A04 est conservé.

**Précision sur l’amortissement hérité :** les entrées métalliques dm/dn=0 ne garantissent pas des valeurs natives nulles. Les listings A04 et A05 affichent dm=0,015 pour les triangles métalliques et dm=dn=0,015 pour les quadrilatères de façade. Le radôme A05 emploie dm/dn=10⁻²⁰ et apparaît nul à l’affichage. Cette observation corrige l’interprétation des zéros de carte, sans changer les anciens calculs. Son effet sur le déficit énergétique n’est pas identifié ; il devra être testé explicitement, sans attribuer ce déficit à une dissipation physique réelle.

Outillage conservé : r0 échoue avant solveur sur un nom de champ de poutres ; r1 COMP_FREE est rejeté pour15 avertissements d’alignement des champs ; r2 rejette deux Starter d’autocontact pour une variable TH CE non disponible. Les trois cas dynamiques r2 terminés sont réutilisés ; les six autres utilisent r3 après retrait de cette seule variable de sortie. Les six convertisseurs T02 r3 échouent par accès mémoire ; leurs CSV incomplets et journaux restent intacts. recover_aircraft_a05_history.py relit les enregistrements binaires big-endian et vérifie chaque ligne de T01 contre le CSV natif à6×10⁻⁷ près relatif avant d’exporter la seule ligne initiale T02 dans un **autre fichier**. Aucun pas synthétique ni Engine additionnel. La continuation de l’observateur conserve matériaux et historique, ses états postérieurs restent exclus.

Les premiers audits composites avaient une collision de nom entre ratio d’énergie et diagnostic de face ; leurs valeurs de ratio local étaient incorrectes, leurs critères pass/fail ne changent pas. La relecture autoritative **cached_review/review.json** recalcule ces ratios à partir des NPZ, épingle les premiers audits et conserve l’erreur. La collecte de tenseurs écarte aussi les cellules virtuelles RBE3 d’ID0 ; leurs champs nuls ne changeaient pas les maxima. Ces erreurs d’outillage ne sont pas des ajustements des résultats physiques.

![Avion entier et comparaison des deux maillages de nez](cached_review/summary_aircraft_a05.png)

La figure utilise les états mécaniques sauvés, déplacement×1 ; la ligne rouge est le plan initial de façade, pas une façade déformée. Les deux états de nez terminaux ont leurs temps distincts conservés dans la provenance. Blender reste une visualisation tant que sa dynamique n’est pas liée à des états mécaniques vérifiés. La localisation en flexion après fracture complète n’est pas validée ; une température imposée n’est pas un incendie calculé ; les tests numériques ne valident pas l’effondrement réel.

## Reprise et publication

Configuration et sources : aircraft_a05_predeclaration.json/source_manifest.json. Sélection retenue : case_selection.json, r2 pour ROUND_METAL/COMP_FREE/COMP_NOSC, r3 pour les six autres. Résultats autoritatifs : cached_review/review.json, NPZ et fichiers natifs conservés. complete_aircraft_a05.py verify contrôle hashes, état, registre et harnais sans solveur. Ne pas relancer les neuf Engines pour publier ou reprendre.

{NEXT}

A05 est la cinquième itération de l’avion entier, le registre atteint124 entrées après vérification. La paire A04+A05 doit être publiée selon l’autorisation existante, échecs compris ; la cadence ne sera remise à zéro qu’après vérification distante de Git, archives et CI. Aucun post sur X ni opération sur Yoremi n’est requis.
''',encoding='utf-8')
    HANDOFF.write_text((OUT/'handoff_template.md').read_text(encoding='utf-8'),encoding='utf-8')
    paths0=[p for p in OUT.rglob('*') if p.is_file()]+[ROOT/'wtc1_simulation_v8/scripts'/name for name in ['run_aircraft_a05.py','audit_aircraft_a05.py','recover_aircraft_a05_history.py','collect_aircraft_a05_tensors.py','review_aircraft_a05_cached.py','plot_aircraft_a05.py','complete_aircraft_a05.py','acquire_aircraft_a05_sources.py']]+[CFG,HANDOFF]+list((ROOT/'wtc1_simulation_v8/input/aircraft_a05_sources').glob('*.json'))
    dump(OUT/'artifact_manifest.json',{'created_utc':now(),'files':[{'path':rel(p),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(paths0)],'excluded':['self','publication_verification.json','mutable state registry cadence','external source PDFs'],'scope':'All own attempts and saved whole-aircraft results, including failed gates; source PDFs pinned separately.'});print({'prepared':True,'files':len(paths0),'old_preserved':n})

def register():
    assert REPORT.exists() and HANDOFF.exists() and not (OUT/'publication_verification.json').exists();preserved()
    for name in ['state.json','publication_cycle.json','experiments/registry.jsonl']:assert sha(ROOT/'harness'/name)==sha(OUT/('before_'+name.split('/')[-1]))
    for row in read(OUT/'artifact_manifest.json')['files']:assert sha(ROOT/row['path'])==row['sha256'],row['path']
    assert harness()['Status']=='PASS';state=read(ROOT/'harness/state.json');cycle=read(ROOT/'harness/publication_cycle.json');assert state['current_iteration']=='AIRCRAFT-A04' and cycle['pending_iterations']==['AIRCRAFT-A04'];s=read(OUT/'cached_review/review.json');t=now();status='completed_whole_aircraft_rounded_reference_radome_with_spatial_material_energy_limits'
    record={'experiment_id':'WTC1-AIRCRAFT-A05','registered_at':t,'status':status,'configuration':rel(CFG),'report':rel(REPORT),'results':rel(OUT/'cached_review/review.json'),'handoff':rel(HANDOFF),'artifact_manifest':rel(OUT/'artifact_manifest.json'),'publication_verification':rel(OUT/'publication_verification.json'),'saved_arrays_mass_connectivity_pass':True,'all_declared_checks_pass':False,'physical_impact_qualified':False,'historical_radome_reconstructed':False,'local_energy_ledger_fully_qualified':False,'spatial_convergence_qualified':False,'cases':9,'horizons_reached':9,'main_solver_jobs':9,'observation_jobs':9,'starter_jobs':12,'old_solver_reruns':0,'old_files_preserved':2878,'half_dt_impulse_difference_fraction':s['comparisons'][0]['impulse_relative_difference'],'half_dt_generated_energy_difference_fraction':s['comparisons'][0]['generated_energy_relative_difference'],'spatial_impulse_difference_fraction':s['comparisons'][1]['impulse_relative_difference'],'spatial_generated_energy_difference_fraction':s['comparisons'][1]['generated_energy_relative_difference'],'self_contact_active_in_window':False,'NIST_outcomes_used_as_target':False,'NIST_nominal_facade_input_dependency':True,'next_iteration':'AIRCRAFT-A06'}
    with (ROOT/'harness/experiments/registry.jsonl').open('a',encoding='utf-8',newline='\n') as f:f.write(json.dumps(record,ensure_ascii=False)+'\n')
    state.update(current_iteration='AIRCRAFT-A05',next_iteration='AIRCRAFT-A06',current_status=status,next_objective=NEXT,updated_at=t);state['aircraft_a05_key_results']=record;state['user_steering_2026_10_05']['next']='AIRCRAFT-A06';state['validated_artifacts'].update(aircraft_a05_report=rel(REPORT),aircraft_a05_results=rel(OUT/'cached_review/review.json'),aircraft_a05_handoff=rel(HANDOFF),aircraft_a05_figure=rel(OUT/'cached_review/summary_aircraft_a05.png'))
    cycle.update(pending_iterations=['AIRCRAFT-A04','AIRCRAFT-A05'],pending_count=2,next_publication_after='A04+A05 ready for authorized publication; include all failed physical and spatial gates',updated_at=t);dump(ROOT/'harness/state.json',state);dump(ROOT/'harness/publication_cycle.json',cycle);verify(True)

def verify(write=False):
    n=preserved();man=read(OUT/'artifact_manifest.json');bad=[r['path'] for r in man['files'] if sha(ROOT/r['path'])!=r['sha256']];before=read(OUT/'before_state.json');state=read(ROOT/'harness/state.json');cycle=read(ROOT/'harness/publication_cycle.json');reg=(ROOT/'harness/experiments/registry.jsonl').read_bytes();prefix=(OUT/'before_registry.jsonl').read_bytes();suffix=reg[len(prefix):].decode().splitlines();s=read(OUT/'cached_review/review.json');v=harness();protected=[k for k in before if k.endswith('_key_results')]+['source_archive','evidence_policy','open_limitations','deferred_thermal_branch'];cadence=(cycle['pending_iterations']==['AIRCRAFT-A04','AIRCRAFT-A05'] and cycle['pending_count']==2) or (cycle['pending_iterations']==[] and cycle['pending_count']==0 and cycle['last_published_iteration']=='AIRCRAFT-A05')
    checks={'new_artifact_hashes':not bad,'old_files_preserved':n==2878,'predeclaration_unchanged':sha(CFG)==read(OUT/'declaration_guard.json')['sha256'],'sources_unchanged':all(sha(ROOT/r['path'])==r['sha256'] for r in read(OUT/'source_manifest.json')['local_inputs']),'registry_append_only':reg.startswith(prefix),'one_A05_record':len(suffix)==1 and json.loads(suffix[0])['experiment_id']=='WTC1-AIRCRAFT-A05','state_route':state['current_iteration']=='AIRCRAFT-A05' and state['next_iteration']=='AIRCRAFT-A06','old_limits_and_results_preserved':all(before[k]==state[k] for k in protected),'saved_states_and_signed_tensor_review':s['integrity_only_pass'] and read(OUT/'saved_tensor_and_geometry_review.json')['pass'] and read(OUT/'saved_result_review.json')['pass'],'nine_horizons_observed':all(r['requested_horizon_reached'] for r in s['cases']),'all_first_audits_preserved':all(sha(ROOT/r['original_audit'])==r['original_sha256'] for r in s['saved_first_audit_proof']),'failed_gates_visible':not s['all_declared_checks_pass'] and not s['comparisons'][1]['impulse_pass'] and not s['comparisons'][1]['energy_pass'] and not s['local_energy_ledger_fully_qualified'],'no_physical_or_historical_claim':not s['physical_impact_qualified'] and not s['historical_radome_reconstructed'],'cadence_ready_or_remotely_confirmed':cadence,'no_NIST_outcome_fit':not read(CFG)['NIST_outcomes_used_as_target'],'harness_pass':v['Status']=='PASS'}
    result={'created_utc':now(),'pass':all(checks.values()),'integrity_only':True,'checks':checks,'files_checked':len(man['files']),'old_files_checked':n,'harness':v,'physical_impact_qualified':False,'local_energy_ledger_fully_qualified':False,'spatial_convergence_qualified':False,'pending_Github_iterations':cycle['pending_count'],'next_iteration':'AIRCRAFT-A06'};assert result['pass'],result
    if write:dump(OUT/'publication_verification.json',result)
    print(json.dumps(result,ensure_ascii=False,indent=2))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('action',choices=['prepare','register','verify']);a=p.parse_args();globals()[a.action]()
