"""Seal metal-only qualification and retain DKT/native Starter failures."""
from run_aircraft_a26 import *
from finalize_aircraft_a22 import verify_files
REPORT=OUT/'rapport_aircraft_a26.md'
HANDOFF=ROOT/'harness/handoffs/WTC1_AIRCRAFT_A26_HANDOFF.md'

def route():
    return ('AIRCRAFT-A27 : reprendre metal_qualification_review.json. Les9témoins métal TYPE20 HA8 passent masse, inertie discrète/continue, libreXYZ, translation, moment physique, bilan natif, membrane/flexion indépendantes et raffinements. '
      'DKT_S3 élimine RKE mais son bilan de flexion et son critère strict de quantité de mouvement échouent; conserver ces9calculs. La tentative TYPE20 w1 s’arrête au Starter sur des champs réservés non blancs; w2 corrige uniquement le format et réussit. '
      'Qualifier maintenant la peau orthotrope LAW25 héritée en TYPE22 HA8 avec volumes/densité/orientation/quadrature explicites, sans supposer une équivalence matérielle. LAW25/4 est une référence élastique, pas la rupture historique qualifiée. '
      'Puis vérifier le sandwich/cœur et les24racines/144ancres réelles inventoriées A25, sans montage entier d’une liaison non qualifiée, ni prolongation d’un état A21 invalide. '
      'Les paramètres de rupture, matériaux, gravité, intérieur porteur et contacts des fragments restent ouverts. Nouveau départ entier intact seulement après bilans; mesurer le coût avant tout calcul long. '
      'Objectif vidéo3D10secondes physiques incomplet, meilleur entier A20=20ms. Publication suivante A26+A27 après intégrité. Aucun dommage connu comme cible, aucune compensation de masse ou RKE.')

def prepare():
    guard();assert not REPORT.exists();p=read(OUT/'preservation_verification.json');r=read(OUT/'metal_qualification_review.json');assert p['pass'] and r['metal_prototype_pass'];h=harness();assert h['Status']=='PASS';dump(OUT/'harness_after_calculation.json',h)
    st=read(ROOT/'harness/state.json');cy=read(ROOT/'harness/publication_cycle.json');old=read(OUT/'before_state.json');oc=read(OUT/'before_publication_cycle.json');assert st['current_iteration']=='AIRCRAFT-A25' and cy['last_published_iteration']=='AIRCRAFT-A25' and cy['pending_count']==0 and cy['pending_iterations']==[]
    protected=[k for k in old if k.endswith('_key_results')]+['source_archive','evidence_policy','open_limitations','deferred_thermal_branch','objective1_video_10s'];assert all(st[k]==old[k] for k in protected);assert (ROOT/'harness/experiments/registry.jsonl').read_bytes()==(OUT/'before_registry.jsonl').read_bytes();dump(OUT/'before_state_for_registration.json',st);dump(OUT/'before_publication_cycle_for_registration.json',cy);proof=ROOT/'outputs/github_publication/updates_2026-10-10_aircraft_a24_a25/final_remote_verification.json';assert read(proof)['pass'];dump(OUT/'publication_during_declaration.json',{'created_utc':now(),'proof':rel(proof),'sha256':streamsha(proof),'changed_harness_metadata_only':True,'old_scientific_results_preserved':True,'original_before_snapshots_preserved':True})
    rows=[{'revision':rev,**x} for rev,key in [('w0','DKT_cases_preserved'),('w2','native_HA8_cases')] for x in r[key]];executions=[{'path':rel(x),**read(x)} for x in sorted(OUT.glob('w*/*/*.execution.json'))];dump(OUT/'runtime_manifest.json',{'created_utc':now(),'software':'OpenRadioss native double precision win64 20260728','CPU_threads':1,'GPU':False,'execution_seconds_sum':sum(x.get('seconds',0) for x in executions),'executions':executions,'executables':[{'path':rel(x),'bytes':x.stat().st_size,'sha256':streamsha(x)} for x in [RUNTIME/'starter_win64.exe',RUNTIME/'engine_win64.exe',RUNTIME/'th_to_csv_win64.exe',RUNTIME/'anim_to_vtk_win64.exe']]})
    a={'created_utc':now(),'iteration':'AIRCRAFT-A26','status':'completed_metal_solidshell_controls__composite_and_real_root_pending','native_controls':18,'native_individual_sets_passed':sum(x['pass'] for x in rows),'native_energy_balances_passed':sum(x['checks']['native_full_balance'] for x in rows),'metal_HA8_native_controls_passed':9,'metal_scope_qualified':True,'DKT_failures_preserved':5,'Starter_only_failed_attempts':1,'native_field_samples':len(read(OUT/'native_fields_review.json')['samples']),'composite_skin_qualified':False,'whole_insertion_ready':False,'new_whole_impact_executed':False,'old_native_solver_reruns':0,'physical_strength_and_fracture_qualified':False,'objective1_complete':False,'next_iteration':'AIRCRAFT-A27'};dump(OUT/'scientific_assessment.json',a);dump(OUT/'campaign_review.json',{'created_utc':now(),'cases':rows,'assessment':a,'metal_qualification_review':rel(OUT/'metal_qualification_review.json'),'failed_attempts_preserved':True});dump(OUT/'objectif1_route.json',{'created_utc':now(),'target_physical_s':10,'best_whole_physical_s':.0200001220703125,'complete':False,'next':route()})
    table='\n'.join(f"| {x['revision']} / {x['case']} | {x['maximum_residual_J']:.9g} | {'réussi' if x['pass'] else '**échoué**: '+', '.join(k for k,v in x['checks'].items() if not v)} |" for x in rows)
    REPORT.write_text(f'''# AIRCRAFT-A26 — plaques sans inertie nodale de rotation

**18 nouveaux calculs natifs complets**, avec une tentative Starter conservée. Les **neuf témoins métal volumique TYPE20 HA8 passent tous leurs contrôles**, dont inertie physique, moment libreXYZ, énergie, traction et flexion indépendantes, raffinement spatial et temporel. Les neuf témoins triangulaires DKT_S3 et leurs cinq échecs sont conservés. Qualification limitée à la plaque métallique isolée; aucun transfert entier ni vidéo10secondes physiques.

## 1. Faits directement observés ou transcrits

Graine1102051, aucun tirage aléatoire. Plaque10×10×0,5mm, volume50mm³, masse0,139g. DKT_S3 w0: triangles à translations, rotation calculée via les voisins. TYPE20 w2: hexaèdres HA8 à translations, maillages6×6×1 et12×12×1. Aucun matériau de l'avion entier n'est remplacé. CPU1thread, aucun GPU, ADMAS ou mise à l'échelle. Entrées, sorties, scripts générateurs, vitesses, masses, temps d'exécution et critères sont conservés.

TYPE20 w1 s'arrête sur l'avertissement100214: des colonnes réservées contiennent des zéros au lieu d'espaces. Aucun Engine w1 lancé. Une nouvelle déclaration w2 conserve géométrie, matériau et seuils, corrige seulement ces champs et passe le Starter sans avertissement. Aucun ancien solveur répété. Les{a['native_field_samples']}échantillons de champs w0/w2 sont finis, sans suppression, et passent les identités de coordonnées avec borne explicite d'impression. Préservation de{p['files']}fichiers antérieurs, soit{p['bytes_hashed']/1e9:.3f}Go.

La publication A24+A25 est vérifiée pendant la déclaration A26: elle met à jour la cadence et les métadonnées de publication, sans changer les résultats scientifiques ou le registre. Les snapshots initiaux A26 sont gardés, et une nouvelle référence de registre après publication est vérifiée séparément.

## 2. Résultats d'un modèle officiel

La [théorie DKT_S3](https://help.altair.com/hwsolvers/rad/topics/solvers/rad/theory_element_3_node_triangle_without_rot_dof_r.htm) décrit la flexion dérivée des translations de voisins. [TYPE20](https://help.altair.com/hwsolvers/rad/topics/solvers/rad/prop_type20_tshell_starter_r.htm) décrit HA8 et le choix de direction d'épaisseur. Les témoins vérifient ces formulations avec références indépendantes; leurs intitulés ne suffisent pas à la qualification. Aucun dommage connu ou résultat NIST n'est une cible.

## 3. Affirmations provenant des archives locales

Aucune nouvelle vidéo ou photographie historique. Matériau LAW2 repris en lecture seule du fichier source A20 identifié dans material_source_addendum.json. Les24racines/144ancres réelles inventoriées A25 restent disponibles pour la suite. La plaque d'essai n'est pas une nouvelle identification de la structure AA11.

## 4. Hypothèses propres au modèle

LAW2 métallique hérité:rho0,00278g/mm³, E73100MPa, nu0,33, seuil324MPa, écrouissage nul, rupture absente. DKT et HA8 conservent volume et densité; leurs masses nodales diffèrent et sont calculées explicitement par intégration des aires/volumes. Aucun réajustement des inerties. Pour HA8, le tenseur discret tient compte des deux faces d'épaisseur; il est confronté au tenseur continu du même parallélépipède, au seuil2%, sans déclaration d'exactitude continue.

Rotations libres10rad/ms pendant0,05ms surXYZ, translation[-200,5,2]m/s, pasY réduit. Traction affine epsilon_x0,001 avec contractions de Poisson. Flexion cylindrique de courbure0,001/mm, déplacements volumétriques cohérents avec sigma_z=0 au premier ordre et courbure_y=0. Référence de flexion D=Et³/[12(1−nu²)], sans calage à un résultat natif. Une couche géométrique d'épaisseur et huit points d'intégration pour HA8; direction s bottom-to-top suivant la convention native. Le matériau composite et les attaches ne sont pas concernés par cette qualification.

## 5. Résultats dérivés

| Contrôle | Résidu énergétique maximal(J) | Résultat |
|---|---:|---|
{table}

Les deux formulations ne produisent aucune RKE nodale indépendante. DKT passe le moment physique libre mais échoue au critère absolu strict de quantité de mouvement dans les rotationsX/Y etY à pas réduit. L'historique natif confirme une dérive maximaleY d'environ1,637529e-8N·s; cet échec n'est pas seulement celui d'une somme de valeurs de vitesse imprimées. Ses flexions retrouvent la rigidité intérieure de référence mais échouent au bilan global natif; enN12 le résidu maximal vaut0,000545413144J, avec travail extérieur final négatif. Aucun correctif comptable n'est appliqué.

Les neuf témoins HA8 passent les critères de masse, énergie complète, quantité de mouvement, moment physique, énergie initiale discrète/continue, traction et flexion. Leur pas réduit est{r['refinement']['actual_dt_ratio']:.9g}fois le pas initial, différence de moment{r['refinement']['physical_L_difference_kg_m2_s']:.9g}kg·m²/s et d'énergie{r['refinement']['energy_difference_J']:.9g}J; les seuils initialement déclarés passent. L'écart N6/N12 de traction est{100*r['mesh'][0]['difference_fraction']:.9g}% et celui de flexion{100*r['mesh'][1]['difference_fraction']:.9g}%, sous5%. Ces réussites sont propres à la plaque isolée et aux sollicitations déclarées.

## 6. Contradictions et informations manquantes

La suppression des rotations nodales indépendantes ne garantit pas à elle seule un bilan correct: les échecs DKT en témoignent. HA8 réussit sur métal, mais ne qualifie pas la peau orthotrope LAW25, la jonction au cœur, les attachés réels ou les matériaux à rupture. Une nouvelle formulation composite nécessite mêmes volumes, orientation, densité et quadrature documentés, avec contrôles propres. La référence LAW25/4 utilisée dans les témoins précédents est élastique, pas une loi de rupture historique validée. L'avion, la façade, la gravité, l'intérieur porteur et les contacts de fragments restent à qualifier. Le meilleur calcul entier demeure A20=20ms, avec les échecs locaux A21 préservés. Aucun état invalide n'est prolongé pour fabriquer une vidéo10secondes.

{route()}
''',encoding='utf-8');HANDOFF.write_text('# Reprise AIRCRAFT-A26 → AIRCRAFT-A27\n\nRapport: '+rel(REPORT)+'\nRésultats: '+rel(OUT/'metal_qualification_review.json')+'\n\n'+route()+'\n',encoding='utf-8');files=[x for x in OUT.rglob('*') if x.is_file()]+list((ROOT/'wtc1_simulation_v8/scripts').glob('*aircraft_a26*.py'))+list((ROOT/'wtc1_simulation_v8/data').glob('aircraft_a26*.json'))+[HANDOFF];dump(OUT/'artifact_manifest.json',{'created_utc':now(),'files':[{'path':rel(x),'bytes':x.stat().st_size,'sha256':streamsha(x)} for x in sorted(set(files))]});print({'A26_prepared':True,'metal_scope_pass':True,'whole_scope_pass':False},flush=True)

def register():
    guard();n=verify_files(read(OUT/'artifact_manifest.json')['files']);st=read(ROOT/'harness/state.json');cy=read(ROOT/'harness/publication_cycle.json');assert st==read(OUT/'before_state_for_registration.json') and cy==read(OUT/'before_publication_cycle_for_registration.json');reg=ROOT/'harness/experiments/registry.jsonl';assert reg.read_bytes()==(OUT/'before_registry.jsonl').read_bytes();a=read(OUT/'scientific_assessment.json');t=now();record={'experiment_id':'WTC1-AIRCRAFT-A26','registered_at':t,'configuration':rel(CFG),'configurations':[rel(q) for q in sorted((ROOT/'wtc1_simulation_v8/data').glob('aircraft_a26*.json'))],'report':rel(REPORT),'results':rel(OUT/'metal_qualification_review.json'),'handoff':rel(HANDOFF),'artifact_manifest':rel(OUT/'artifact_manifest.json'),'publication_verification':rel(OUT/'publication_verification.json'),**a}
    with reg.open('a',encoding='utf-8',newline='\n') as f:f.write(json.dumps(record,ensure_ascii=False)+'\n')
    st.update(current_iteration='AIRCRAFT-A26',next_iteration='AIRCRAFT-A27',current_status=a['status'],next_objective=route(),updated_at=t);st['aircraft_a26_key_results']=record;st['validated_artifacts'].update(aircraft_a26_report=rel(REPORT),aircraft_a26_results=rel(OUT/'metal_qualification_review.json'),aircraft_a26_handoff=rel(HANDOFF));cy['pending_iterations'].append('AIRCRAFT-A26');cy.update(pending_count=1,updated_at=t,next_publication_after='AIRCRAFT-A26+AIRCRAFT-A27 verified');dump(ROOT/'harness/state.json',st);dump(ROOT/'harness/publication_cycle.json',cy);verify(n)

def verify(n=None):
    guard();n=n or verify_files(read(OUT/'artifact_manifest.json')['files']);st=read(ROOT/'harness/state.json');old=read(OUT/'before_state_for_registration.json');cy=read(ROOT/'harness/publication_cycle.json');oc=read(OUT/'before_publication_cycle_for_registration.json');reg=(ROOT/'harness/experiments/registry.jsonl').read_bytes();prefix=(OUT/'before_registry.jsonl').read_bytes();tail=reg[len(prefix):].decode('utf-8').splitlines();h=harness();protected=[k for k in old if k.endswith('_key_results')]+['source_archive','evidence_policy','open_limitations','deferred_thermal_branch'];checks={'new_hashes':True,'old_preservation':read(OUT/'preservation_verification.json')['pass'],'old_results':all(st[k]==old[k] for k in protected),'single_registry_append':reg.startswith(prefix) and len(tail)==1 and json.loads(tail[0])['experiment_id']=='WTC1-AIRCRAFT-A26','route':st['current_iteration']=='AIRCRAFT-A26' and st['next_iteration']=='AIRCRAFT-A27','objective_preserved':st['objective1_video_10s']==old['objective1_video_10s'],'harness':h['Status']=='PASS','pending':cy['pending_iterations']==['AIRCRAFT-A26'] and cy['pending_count']==1,'publication_preserved':all(cy[k]==oc[k] for k in ['last_published_iteration','last_published_commit','last_published_release'])};p={'created_utc':now(),'pass':all(checks.values()),'integrity_only':True,'checks':checks,'new_files_verified':n,'old_files_verified':read(OUT/'preservation_verification.json')['files'],'harness':h,'metal_scope_qualified':True,'whole_insertion_ready':False,'objective1_complete':False};assert p['pass'],checks;dump(OUT/'publication_verification.json',p);print(p,flush=True)

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('action',choices=['prepare','register','verify']);globals()[p.parse_args().action]()
