"""Seal and register the new coupled20ms fragment calculation and native movie."""
import json
from run_aircraft_a18 import *
REPORT=OUT/'rapport_aircraft_a18.md';HANDOFF=ROOT/'harness/handoffs/WTC1_AIRCRAFT_A18_HANDOFF.md'
NEXT="AIRCRAFT-A19 : objectif vidéo3D des10 premières secondes physiques actif/incomplet. A18 a intégré624 liaisons cohésives dans le radôme et effectué un impact20ms avec fragments natifs et MP4/GIF, mais l'IE native du radôme devient négative dès12,97032ms et finit à-42,148524MJ. Priorité immédiate : expliquer/corriger ce défaut avant prolongement. Lire negative_energy_diagnostic.json et les états/bilans déjà conservés ; séparer déformation de LAW25/TYPE51/cœur, cinématique de rotation et travail de contraintes, sans relancer A17/A18 ni inventer RKE ou G pour fermer un déficit. Le domaine métal/façade, l'autocontact et les interfaces restent également non qualifiés. Modifier la mécanique impose un nouveau départ intact et déclaré ; seuls des continuations inchangées peuvent réutiliser un checkpoint. Ensuite viser100ms,1s,10s selon le domaine atteint ; ajouter gravité/intérieur réellement modélisé avant les secondes, annoncer le coût avant calcul long, sauver des checkpoints et réduire les sorties sans mass scaling. Aucune cible historique. G50N/mm non mesuré, cœur aux arêtes absent, fissures restreintes aux triangles, contact initial Inacti1000 non qualifié, critère d'offset0,001mm échoué à0,001195mm et quatre canaux de part au lieu de neuf annoncés : conserver toutes ces limites. La vidéo est explicitement marquée bilan énergétique échoué, poses natives à échelle1. Publication A12+A13 intacte ; A14 à A18 en attente."

def check_files(rows):
    for r in rows:
        p=ROOT/r['path'];assert p.is_file() and p.stat().st_size==r['bytes'] and streamsha(p)==r['sha256'],r['path']
    return len(rows)

def prepare():
    guard();assert not REPORT.exists() and not HANDOFF.exists() and not (OUT/'artifact_manifest.json').exists();p=read(OUT/'preservation_verification.json');r=read(OUT/'r0'/CASE/'review.json');v=read(OUT/'video/video_audit.json');rend=read(OUT/'video/render_manifest.json');cfg=read(CFG);ini=read(OUT/'r0'/CASE/'initial_native_review.json');assert p['pass'] and v['pass'] and not v['objective1_complete'] and read(OUT/'visual_QA.json')['decoded_contact_sheet_inspected'];assert harness()['Status']=='PASS'
    wall=read(OUT/'r0'/CASE/'engine.log.execution.json')['seconds'];fc=r['final_fragment_connectivity'];table='\n'.join(f"| {k} | {'réussi' if val else '**échoué**'} |" for k,val in r['checks'].items())
    assess={'created_utc':now(),'new_whole_aircraft_jobs':1,'fresh_intact_start':True,'native_horizon_s':r['end_ms']*.001,'native_radome_separation':fc['deleted_cohesive_strips']>0,'detached_radome_groups':fc['detached_components'],'mass_bearing_shells_not_deleted':r['checks']['mass_bearing_shells_not_deleted'],'all_declared_checks_pass':r['all_declared_checks_pass'],'failed_checks':r['failed_checks'],'global_energy_pass':r['checks']['global_energy'],'local_energy_pass':r['checks']['local_energy'],'initial_mass_CG_inertia_pass':all(ini['checks'].values()),'offset_kinematics_pass':r['checks']['offset_rotation_distance_tolerance'],'physical_G_measured':False,'whole_aircraft_impact_qualified':False,'metal_fracture_modelled':False,'tower_interior_modelled':False,'gravity_modelled':False,'historical_conditions_identified':False,'objective1_target_s':10,'objective1_complete':False,'old_solver_reruns':0,'NIST_outcomes_used_as_target':False,'old_failed_gates_retained':True,'parallel_Boeing_module_integrated':False,'main_engine_wall_s':wall};dump(OUT/'scientific_assessment.json',assess)
    neg=read(OUT/'negative_energy_diagnostic.json');assess.update(negative_native_radome_IE_detected=True,negative_IE_cause_identified=False,negative_IE_diagnostic=rel(OUT/'negative_energy_diagnostic.json'));dump(OUT/'scientific_assessment.json',assess)
    dump(OUT/'objectif1_route.json',{'created_utc':now(),'target_physical_s':10,'new_exploratory_coverage_s':r['end_ms']*.001,'complete':False,'video_physical_s':v['physical_duration_s'],'video_display_s':v['display_duration_s'],'horizon_steps_s':[.02,.1,1,10],'current_failed_gates':r['failed_checks'],'next':NEXT,'observed_20ms_wall_s':wall,'linear_10s_days':wall/20*10000/86400,'linear_projection_is_not_ETA':True})
    REPORT.write_text(f'''# AIRCRAFT-A18 — impact couplé20ms avec séparation du radôme et vidéo3D

Un nouvel impact natif couvre **{r['end_ms']:.9f} ms physiques**, à partir d'un avion intact. Les facettes du nez peuvent maintenant se détacher par rupture de liaisons natives ; leur masse n'est pas retirée. Le MP4/GIF rend ces sorties à échelle1. **L'objectif utilisateur de10 secondes physiques reste actif et incomplet.** Le modèle demeure exploratoire et ses critères échoués sont conservés.

## 1. Faits directement observés ou transcrits

Configuration immutable, graine1102043, zéro tirage. Géométrie générée :42699 nœuds,600 contraintes d'offset RBE2,624 liaisons cohésives sur les arêtes internes de216 triangles de radôme. Les944 appuis aux bords de la façade déformable sont conservés. Un seul nouvel impact entier, aucun ancien Engine relancé. Fin normale, {wall:.3f} s de calcul sur deux threads CPU. Plafond2700s annoncé avant lancement ; aucun calcul GPU.

Starter : zéro erreur et deux avertissements1166/343, tous deux pour l'interface d'autocontact2,576 coins non racinaires coïncidents. **Le critère initial zéro avertissement a échoué et reste faux.** Un contrôle séparé avant Engine a confirmé leur périmètre déclaré et autorisé seulement le diagnostic borné ; il ne remplace pas une qualification physique du contact. Deck et paramètres non modifiés après Starter. Les sources et anciens résultats sont restés intacts :{p['files']} fichiers, {p['bytes_hashed']/1e9:.3f}Go vérifiés par SHA-256.

Les enregistrements de tous les canaux d'histoire CSV ont été comparés au binaire natif ; le redémarrage observateur isolé donne le temps et l'énergie de fin. Ses réactions et impulsions de contact ne sont pas mélangées avec l'histoire principale. {r['verified_geometry_states']} poses contrôlées et rendues ; {v['MP4_frames']} images MP4 H.2642560×720,30Hz,{v['display_duration_s']:.3f}s de lecture ; GIF1280×360. Le film indique le temps physique, les ruptures et groupes détachés. Trois images décodées inspectées. La lecture interactive GUI n'est pas certifiée.

## 2. Résultats d'un modèle officiel et sources primaires

Solveur OpenRadioss v20260728-win64 déjà conservé. Aucun résultat officiel de dégâts n'est choisi comme cible. Les entrées nominales de la façade restent dépendantes de sources NIST comme dans A16 ; cette dépendance d'entrée ne rend pas les résultats indépendants de toute source officielle.

La documentation [RBE2](https://help.altair.com/hwsolvers/rad/topics/solvers/rad/rbe2_starter_r.htm) définit une translation dépendante comprenant l'offset lié à la rotation de son nœud indépendant avec Iflag0. La [TYPE43](https://help.altair.com/hwsolvers/rad/topics/solvers/rad/prop_type43_connect_starter_r.htm) admet des faces coïncidentes ; Ismstr4 est ici employé pour la géométrie mobile. La [LAW117](https://help.altair.com/hwsolvers/rad/topics/solvers/rad/mat_law117_starter_r.htm) fournit la cohésion et la suppression native. Ces définitions ne constituent pas des mesures du Boeing.

Avec [TYPE25](https://help.altair.com/hwsolvers/rad/topics/solvers/rad/inter_type25_starter_r.htm), Inacti1000 ignore les paires initialement pénétrantes et peut les réactiver après sortie puis retour. Ce traitement évite d'inventer une énergie initiale, mais ne garantit pas le contact d'un fragment qui s'est rompu tout en restant dans le jeu initial.

## 3. Affirmations provenant des archives locales

Aucune nouvelle archive vidéo, photographie ou PDF analysée. Les affirmations historiques des archives ne sont pas ajoutées au résultat mécanique. Les contrôles A17 de traction/cisaillement, de travail surfacique, recharge au même pic, aire et demi-pas sont réutilisés sans relance. Ils avaient qualifié une implémentation uniforme Ismstr1, pas le mode mixte, les rotations ou les propriétés du vrai radôme. Leurs limites restent présentes après le changement Ismstr4.

La première procédure Starter a arrêté son wrapper sur les deux avertissements attendus ; son journal et son gate faux sont conservés. Le contrôle complémentaire a été écrit avant tout Engine. Une erreur de sélection des sections d'avertissements dans le listing puis une conversion booléenne NumPy pour le rapport initial ont été corrigées dans les nouveaux scripts d'analyse. Après la fin normale de l'Engine, le premier lecteur a supposé15 blocs par état ; l'ajout d'une part ne créait pas de nouvelle famille de blocs. Les14 blocs réellement présents ont été lus et tous leurs canaux comparés au CSV, sans relance du solveur. Cet échec de récupération est conservé. La carte héritée TH/PART ne sélectionnait que IE/KE/HE/PW pour la cohésion, au lieu des neuf canaux annoncés ; **le critère de couverture à neuf reste échoué** et la configuration effective distincte documente l'écart. Aucune sortie solveur antérieure n'a été corrigée ou effacée.

## 4. Hypothèses propres au modèle

Chaque triangle du radôme possède ses coins de surface distincts, sauf la racine x2000mm qui reste liée au corps. Deux bandes de cohésion, chacune de largeur0,5mm, relient chaque arête interne aux peaux situées à±4..4,5mm. Aire par bande = longueur initiale d'arête×0,5mm. Les coins de bande sont liés à leur propre coin de facette avec RBE2, Iflag0 et translations111000. Densité cohésive1e−20g/mm² ; aucune masse instrumentale de témoin ni mass scaling ajouté. Surface, volume des couches, matériaux, masses et liaisons RBE3 d'origine conservés. La masse, le centre de gravité et l'inertie initiaux natifs sont comparés séparément au parent.

LAW117 : EN4400N/mm³, ET800N/mm³, TN450MPa, TT100MPa, GI=GII50N/mm ; Imass1,Idel4,Irupt1. **Énergies et résistance tangentielle non mesurées pour l'avion.** Ce sont des hypothèses déclarées reprises d'A17, sans adaptation au résultat. ORTHSTRAIN R20 demeure dans les peaux à l'intérieur des facettes ; travail de cohésion suivi à part mais déjà inclus une seule fois dans IE globale. Ce cumul de deux mécanismes n'est pas calibré comme un modèle réel de rupture du sandwich.

Le cœur8mm reste dans chaque facette ; **la traction entre arêtes de cœur n'est pas modélisée**. Fissures limitées aux arêtes initiales, effet du maillage non qualifié. Métaux/façade sans rupture physique identifiée ; pas de structure intérieure, gravité ou carburant résolu. Vitesse initiale[-200,5,2]m/s, propre au prototype et non déterminée pour l'AA11 historique. Les quatre contacts extérieurs TYPE25 gardent le jeu5mm et la rigidité hérités. L'autocontact du radôme devient TYPE25, jeu9mm, Inacti1000 ; pas d'autocontact de tout l'avion.

Pas de déplacement imposé au couplage. Facteur de pas0,5 hérité, TH0,01ms, animation0,2ms, revue géométrique toutes5 images plus dernière et fin observée. Les critères d'énergie/matériaux/quantité de mouvement A16 sont hérités ; tolérance nouvelle d'offset0,001mm déclarée avant exécution. Aucun critère élargi après réception du résultat.

## 5. Résultats dérivés

Masse totale native :{r['total_mass_kg']:.9f}kg. Le contrôle de masse nodale donne un écart parent de{ini['mass_difference_parent_kg']:.9g}kg ; écart d'inertie relative{ini['inertia_relative_difference_parent']:.9g}. Énergie cohésive et contrainte nulles dans le premier état. Énergie générée avant premier contact extérieur ({r['first_external_contact_history_ms']:.6f}ms) :{r['precontact_maximum_generated_energy_J']:.9g}J. Erreur maximale de rayon d'offset, calculée sur les coordonnées **binaires** :{r['maximum_RBE2_offset_distance_error_mm']:.9g}mm. Les coordonnées VTK arrondies auraient artificiellement dégradé ce contrôle ; elles ne sont pas prises comme référence exacte.

À la fin :**{fc['deleted_cohesive_strips']}/624 bandes rompues**, {fc['connected_components']} composantes du radôme dont **{fc['detached_components']} sans connexion à la racine**, comprenant{fc['detached_facets']} facettes. Le graphe conserve une arête tant qu'au moins une de ses deux peaux reste liée ; les coins de racine partagés sont aussi reliés. Ces nombres sont des résultats du maillage et de la loi d'essai, pas un dénombrement de vrais débris. Toutes les coques porteuses de masse demeurent présentes ; seules les connexions de masse négligeable sont supprimées.

Somme finale des termes énergétiques autres que KE{r['final_generated_energy_J']/1e6:.6f}MJ ; résidu global final{r['final_energy_residual_J']:.6f}J, maximum{r['maximum_energy_residual_J']:.6f}J. **Cette somme est négative : ce n'est pas une énergie produite physiquement acceptable.** Le diagnostic natif isolé retrouve une IE du radôme négative à partir de{neg['first_negative_radome_IE_history_ms']:.6f}ms, finissant à{neg['native_radome_final_IE_J']/1e6:.6f}MJ ; l'IE globale finale vaut{neg['native_global_final_J']['INTERNAL ENERGY']/1e6:.6f}MJ tandis que KE augmente. Le défaut réside dans l'IE de la part radôme, sa cause exacte restant inconnue ; la cohésion a une IE positive. Cet examen de cohérence physique est ajouté comme diagnostic distinct, sans prétendre qu'il était un critère pré-déclaré. Le critère global normalisé par l'énorme KE initiale peut réussir et ne compense pas l'échec du bilan local ni l'IE négative.

IE du seul groupe cohésif final{r['final_cohesive_part_IE_J']:.6f}J. Cette IE comprend stockage et dissipation ; elle n'est pas ajoutée à l'IE globale. PW et une RKE inventée ne compensent aucun déficit. Déplacement maximal échantillonné de façade{r['maximum_facade_displacement_mm']:.6f}mm. Impulsion principale finale de contact{r['final_contact_impulse_main_Ns']}N·s.

| Critère déclaré | Résultat |
|---|---|
{table}

Écart maximal de coordonnées Blender{rend['native_coordinate_max_abs_error_m']:.9g}m ; aucune interpolation de géométrie, pas de physique Blender ou de déplacement amplifié. Chaque pose physique est tenue neuf images pour ralentir la lecture. Temps physique{v['physical_duration_s']:.12f}s, objectif10s. Projection linéaire du coût jusqu'à10s :{wall/20*10000/86400:.3f}jours sur deux threads ; pas une ETA fiable, car contacts, ruptures et domaine structurel peuvent changer fortement.

## 6. Contradictions et informations manquantes

Critères échoués :{'; '.join(r['failed_checks'])}. Leur conservation interdit de présenter cet essai comme l'impact WTC1 validé. L'IE négative impose de diagnostiquer la déformation, la formulation des couches/cœur et les rotations/contraintes avant extension ; elle n'est pas attribuée sans preuve à une cause unique. La tolérance d'offset native échoue à{r['maximum_RBE2_offset_distance_error_mm']:.9g}mm et reste0,001mm. Les paramètres cohésifs et le cœur entre facettes manquent de mesures ; rotation/mode mixte ne sont pas qualifiés par les seuls anciens témoins. Le traitement d'initiale coïncidence ne certifie pas le contact des morceaux après rupture, et l'autocontact de l'ensemble avion est absent. Une ressemblance de l'image ne remplace aucun de ces contrôles.

L'horizon20ms est bien calculé, mais il ne couvre que0,02s sur les10s demandées. Avant les secondes suivantes, les limites métal/façade, les contacts des fragments, les planchers et le noyau, la gravité et les conditions historiques doivent être traités explicitement. Les sorties ne sont ni interpolées ni extrapolées pour remplir une durée absente. {NEXT}
''',encoding='utf-8')
    HANDOFF.write_text(f'''# Reprise WTC1 — AIRCRAFT-A18 → AIRCRAFT-A19

Objectif utilisateur10 secondes physiques en vidéo3D toujours actif/incomplet. Nouveau calcul couplé{r['end_ms']:.9f}ms et MP4/GIF à{v['physical_duration_s']:.12f}s physiques. Ne pas confondre avec{v['display_duration_s']:.3f}s de lecture.

Rapport :{rel(REPORT)} ; config :{rel(CFG)} ; résultats :{rel(OUT/'campaign_review.json')} ; bilan/poses/checkpoints :{rel(OUT/'r0'/CASE)} ; vidéo :{rel(OUT/'video/APERCU_A18_20ms_ralenti.mp4')} ; GIF :{rel(OUT/'video/APERCU_A18_20ms_ralenti.gif')}.

624 connexions natives ajoutées ; {fc['deleted_cohesive_strips']} rompues,{fc['detached_components']} groupes détachés ;600 offsetRBE2. Masse/coques conservées. Critères échoués :{'; '.join(r['failed_checks'])}. Résidu final{r['final_energy_residual_J']:.6f}J ; Gtotal{r['final_generated_energy_J']:.6f}J. Temps CPU mural{wall:.3f}s pour20ms. Pré-déclaration immuable, aucun ancienEngine relancé, avertissements et gateStarter faux conservés.

G50N/mm non mesuré, cœur aux arêtes absent, fissure limitée aux triangles, pas de métal/façade qualifiés, pas d'intérieur/gravité. A18 Ismstr4 ; OLD A17contrôlesuniformesIsmstr1n'élargissentpasqualification. Coordonnées binaires pour distanceRBE2 ; VTK arrondi seul faux positif. Toutes les règles, données et limites antérieures préservées :{p['files']}fichiers,{p['bytes_hashed']/1e9:.3f}Go.

{NEXT}
''',encoding='utf-8')
    scripts=['run_aircraft_a18.py','prepare_aircraft_a18_overlap_gate.py','review_aircraft_a18.py','prepare_aircraft_a18_media_scripts.py','encode_aircraft_a18.py','verify_aircraft_a18_preservation.py','finalize_aircraft_a18.py','diagnose_aircraft_a18_energy.py']
    files=[p for p in OUT.rglob('*') if p.is_file()]+[CFG,HANDOFF]+[ROOT/'wtc1_simulation_v8/scripts'/s for s in scripts]+[ROOT/'wtc1_3d_v4/scripts/render_aircraft_a18.py']
    dump(OUT/'artifact_manifest.json',{'created_utc':now(),'files':[{'path':rel(p),'bytes':p.stat().st_size,'sha256':streamsha(p)} for p in sorted(set(files))]});print({'prepared':True,'new_files':len(set(files))},flush=True)

def register():
    guard();n=check_files(read(OUT/'artifact_manifest.json')['files']);assert harness()['CurrentIteration']=='AIRCRAFT-A17';st=read(ROOT/'harness/state.json');cy=read(ROOT/'harness/publication_cycle.json');assert st['next_iteration']=='AIRCRAFT-A18';reg=ROOT/'harness/experiments/registry.jsonl';prefix=(OUT/'before_registry.jsonl').read_bytes();assert reg.read_bytes()==prefix
    t=now();a=read(OUT/'scientific_assessment.json');v=read(OUT/'video/video_audit.json');rec={'experiment_id':'WTC1-AIRCRAFT-A18','registered_at':t,'status':'completed_exploratory_native_facet_separation_whole20ms_and_3D_MP4_GIF__10s_goal_open','configuration':rel(CFG),'report':rel(REPORT),'results':rel(OUT/'campaign_review.json'),'handoff':rel(HANDOFF),'artifact_manifest':rel(OUT/'artifact_manifest.json'),'publication_verification':rel(OUT/'publication_verification.json'),**a,'next_iteration':'AIRCRAFT-A19'}
    with reg.open('a',encoding='utf-8',newline='\n') as f:f.write(json.dumps(rec,ensure_ascii=False)+'\n')
    st.update(current_iteration='AIRCRAFT-A18',next_iteration='AIRCRAFT-A19',current_status=rec['status'],next_objective=NEXT,updated_at=t);st['aircraft_a18_key_results']=rec;st['objective1_video_10s']={'requested_physical_duration_s':10,'current_native_whole_duration_s':v['physical_duration_s'],'status':'active_incomplete','interim_MP4':v['files'][0]['path'],'interim_GIF':v['files'][1]['path'],'route':rel(OUT/'objectif1_route.json'),'physical_goal_complete':False};st['validated_artifacts'].update(aircraft_a18_report=rel(REPORT),aircraft_a18_results=rel(OUT/'campaign_review.json'),aircraft_a18_handoff=rel(HANDOFF))
    assert 'AIRCRAFT-A18' not in cy['pending_iterations'];cy['pending_iterations'].append('AIRCRAFT-A18');cy.update(pending_count=len(cy['pending_iterations']),updated_at=t,next_publication_after='A14+A15 and A16+A17 pairs pending; A18 pending next pair;10s objective still incomplete');dump(ROOT/'harness/state.json',st);dump(ROOT/'harness/publication_cycle.json',cy);verify(n)

def verify(n=None):
    guard();n=n or check_files(read(OUT/'artifact_manifest.json')['files']);st=read(ROOT/'harness/state.json');old=read(OUT/'before_state.json');cy=read(ROOT/'harness/publication_cycle.json');oc=read(OUT/'before_publication_cycle.json');reg=(ROOT/'harness/experiments/registry.jsonl').read_bytes();prefix=(OUT/'before_registry.jsonl').read_bytes();tail=reg[len(prefix):].decode('utf-8').splitlines();v=harness();protected=[k for k in old if k.endswith('_key_results')]+['source_archive','evidence_policy','open_limitations','deferred_thermal_branch']
    checks={'new_artifact_hashes':True,'all_old_files_preserved':read(OUT/'preservation_verification.json')['pass'],'old_policies_and_results_preserved':all(st[k]==old[k] for k in protected),'single_registry_append':reg.startswith(prefix) and len(tail)==1 and json.loads(tail[0])['experiment_id']=='WTC1-AIRCRAFT-A18','route':st['current_iteration']=='AIRCRAFT-A18' and st['next_iteration']=='AIRCRAFT-A19','10s_objective_incomplete':not st['objective1_video_10s']['physical_goal_complete'],'harness_pass':v['Status']=='PASS','pending_prior_preserved':cy['pending_iterations']==oc['pending_iterations']+['AIRCRAFT-A18'] and cy['pending_count']==len(cy['pending_iterations']),'remote_baseline_unchanged':all(cy[k]==oc[k] for k in ['last_published_iteration','last_published_commit','last_published_release'])}
    proof={'created_utc':now(),'pass':all(checks.values()),'integrity_only':True,'checks':checks,'new_files_verified':n,'old_files_verified':read(OUT/'preservation_verification.json')['files'],'harness':v,'external_publication_performed':False,'objective1_complete':False,'physical_impact_qualified':False};assert proof['pass'];dump(OUT/'publication_verification.json',proof);print({k:proof[k] for k in ['pass','new_files_verified','old_files_verified','harness']},flush=True)

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('action',choices=['prepare','register','verify']);globals()[p.parse_args().action]()
