"""Preserve rejected TYPE22 positions, use regular homogeneous layers and native integration."""
from run_aircraft_a27 import *

def main():
    source=Path(__file__).with_name('run_aircraft_a27.py');target=source.with_name('test_aircraft_a27_regular_layers.py');cfg=ROOT/'wtc1_simulation_v8/data/aircraft_a27_regular_layers.json';assert not target.exists() and not cfg.exists();h=harness();assert h['Status']=='PASS';dump(OUT/'harness_before_regular_layers.json',h);d=OUT/'w0/FREE_ROTATION_X_N12';assert read(d/'starter_gate.json')['warnings']==1 and not (d/'engine.log').exists();c=read(CFG);c.update(revision='w1',declared_utc=now(),parent_configuration_sha256=streamsha(CFG),layer_correction='Starter674 rejects manually positioned Gauss weights as irregular physical layer ratios. Use three equal-thickness homogeneous layers with automatic positions and native HA8 integration. Same homogeneous LAW25, density, phi90, global thickness, no physical layup claim; no original Engine ran. Analytic bending reference unchanged.');c['changes']['property']='TYPE22 HA814 Icstr010 Inpts232 Ipos0, three regular homogeneous layers of relative thickness1/3, z input0 (native auto positions); native quadrature checked by elastic references, not presumed equivalent to previous rejected weights.';dump(cfg,c);dump(OUT/'regular_layers_guard.json',{'created_utc':now(),'sha256':streamsha(cfg),'before_new_native_solvers':True});s=source.read_text(encoding='utf-8');audit=[]
    replacements=[('aircraft_a27_predeclaration.json','aircraft_a27_regular_layers.json'),("OUT/'declaration_guard.json'","OUT/'regular_layers_guard.json'"),("OUT/'w0'","OUT/'w1'"),("OUT/'native_case_summary.json'","OUT/'native_case_summary_w1.json'"),("OUT/'runner_derivation.json'","OUT/'runner_w1_derivation.json'"),("OUT/'review_derivation.json'","OUT/'review_w1_derivation.json'"),("ii(0,0,1),ff(.833333333333)","ii(0,0,0),ff(.833333333333)"),("[(5/18,-np.sqrt(3/5)/2),(4/9,0),(5/18,np.sqrt(3/5)/2)]","[(1/3,0)]*3")]
    for old,new in replacements:
        count=s.count(old);assert count>0,old;s=s.replace(old,new);audit.append({'old':old,'new':new,'count':count})
    ast.parse(s);target.write_text(s,encoding='utf-8',newline='\n');dump(OUT/'regular_layers_derivation.json',{'created_utc':now(),'source':rel(source),'source_sha256':streamsha(source),'target':rel(target),'target_sha256':streamsha(target),'changes':audit,'original_Starter674_preserved':True,'native_solver_reruns':0});print({'A27_regular_layers_declared':True,'original_rejected_positions_retained':True},flush=True)

if __name__=='__main__':main()
