"""Correct listing summary double-count; reuse preserved Starter, never rerun it."""
from test_aircraft_a21_root_type2 import *

def main():
    tguard();cid='SPOT2_X';d=OUT/'w5'/cid;n='A21_ROOT_'+cid;assert not (d/'engine.log').exists()
    s=(d/(n+'_0000.out')).read_text(errors='replace');ids=re.findall(r'WARNING ID\s*:\s*(\d+)\s*\n\*\* WARNING',s)
    assert ids==['86']*8 and read(d/'edge_projection_audit.json')['secondary_nodes_all_native_attached']
    assert read(d/'starter_gate.json')['exit_ok'] and read(d/'starter_gate.json')['errors']==0
    dump(d/'warning_parser_addendum.json',{'created_utc':now(),'before_first_w5_Engine':True,'original_failed_parser_gate_retained':True,'source_warning_count':len(ids),'source_warning_ids':ids,'failure_cause':'The summary also contains WARNING ID86. Count actual warning descriptions only, not the summary. No new Starter, no mechanical change, no threshold change.','controlled_execution_allowed':True,'strict_zero_warning_pass':False})
    en=env();en['OMP_NUM_THREADS']='1';en['RAD_HMPP_DOMAINS']='1';assert execute(RUNTIME/'engine_win64.exe',['-i',n+'_0001.rad'],d,'engine.log',90,en);assert 'NORMAL TERMINATION' in (d/'engine.log').read_text(errors='replace');assert execute(RUNTIME/'th_to_csv_win64.exe',[n+'T01'],d,'converter.log',90,en)
    H=histories(d/(n+'T01.csv'));T=H['time'];v=np.column_stack(list(H.values()))[:,23:83].reshape(len(T),10,6);A=histories(OUT/'w2/REFERENCE_X/A21_ROOT_REFERENCE_XT01.csv');av=np.column_stack(list(A.values()))[:,23:83].reshape(len(A['time']),-1);va=np.column_stack([np.interp(T,A['time'],av[:,j]) for j in range(60)]).reshape(len(T),10,6)
    total=sum(H[k] for k in ['KINETIC ENERGY','ROTATION ENERGY','INTERNAL ENERGY','HOURGLASS ENERGY','SPRING ENERGY'])*.001;EW=H['EXTERNAL WORK']*.001;R=total-total[0]-EW;ref=np.load(OUT/'w2/REFERENCE_X/energy_history_SI.npz');refE=np.interp(T,ref['time_ms'],ref['native_total_J']);delta=total-refE;a=read(TC)['acceptance'];peak=float(refE.max());tol=a['matched_energy_relative']*peak+a['absolute_J'];pos=float(abs(v[:,:,:3]-va[:,:,:3]).max());vel=float(abs(v[:,:,3:]-va[:,:,3:]).max())
    checks={'zero_errors_and_warnings':False,'all_secondary_points_follow_rigid_reference':pos<a['motion_mm'],'all_point_velocities_follow_reference':vel<a['velocity_m_s'],'matched_reference_energy':float(abs(delta).max())<tol,'native_energy_balance':float(abs(R).max())<a['native_energy_balance_relative']*max(float(abs(total).max()),float(abs(EW).max()))+a['absolute_J'],'physical_mass_preserved':bool(abs(H['MASS'][0]-A['MASS'][0])<1e-6*A['MASS'][0]),'no_scaled_mass':bool(np.all(H['ADDED MASS']==0))}
    r={'created_utc':now(),'case':cid,'revision':'w5','search':1,'spot':2,'maximum_matched_displacement_error_mm':pos,'maximum_matched_velocity_error_m_s':vel,'maximum_native_energy_residual_J':float(abs(R).max()),'maximum_matched_energy_error_J':float(abs(delta).max()),'reference_peak_total_J':peak,'native_peak_total_J':float(total.max()),'matched_energy_tolerance_J':tol,'checks':{k:bool(x) for k,x in checks.items()},'pass':all(checks.values()),'energy_motion_mass_checks_pass':all(x for k,x in checks.items() if k!='zero_errors_and_warnings'),'nested_hierarchy_qualified':False,'strength_failure_qualified':False,'whole_cause_proven':False}
    np.savez_compressed(d/'energy_history_SI.npz',time_ms=T,native_total_J=total,reference_total_J=refE,energy_difference_J=delta,residual_J=R);dump(d/'review.json',r);print(r,flush=True)
    for cid in read(TC)['cases'][1:]:one(cid,'w5')
    rows=[read(OUT/'w5'/cid/'review.json') for cid in read(TC)['cases']];dump(OUT/'root_type2_w5_review.json',{'created_utc':now(),'cases':rows,'all_declared_checks_pass':all(r['pass'] for r in rows),'energy_motion_mass_checks_pass':all(r['energy_motion_mass_checks_pass'] for r in rows),'Spot2_energy_motion_mass_pass':all(r['energy_motion_mass_checks_pass'] for r in rows if r['spot']==2),'Spot5_energy_motion_mass_pass':all(r['energy_motion_mass_checks_pass'] for r in rows if r['spot']==5),'strict_zero_warning_pass':False,'edge_extrapolations_explicit':True,'whole_engine_allowed':False,'nested_hierarchy_qualified':False,'physical_root_strength_qualified':False})

if __name__=='__main__':main()
