"""Review the fresh temporal control using unchanged gates, both native and printed energy."""
from run_aircraft_a21_halfdt import *
from review_aircraft_a15 import segments
from audit_aircraft_a03 import topology
PROTOCOL=OUT/'halfdt_review_protocol.json'

def declare():
    hguard();assert not PROTOCOL.exists();dump(PROTOCOL,{'declared_utc':now(),'case':N,'no_solver_change':True,'energy':'All native float32 global rows plus independently verified printed CSV. Old unchanged local gate5% generated+1000J for generated>1000J. No added/inferred RKE.','windows_ms':[[0,10],[10,12.0001]],'momentum':'All main histories only; observer momentum excluded. Distinct contact groups and support cumulative reaction cross-checked against global and facade momentum.','cached_parent_comparison':'A20 on the same true time, never rerun. Maximum time sensitivity and common end values retained even if gates fail.','geometry_sample_target_ms':[0,4,8,12],'skin_energy':'every retained native animation shell field including observer','negative_element_IE_allowance_J':.001,'no_scale_change_or_fracture_added':True,'physical_impact_qualified':False})

def ledger(H):
    terms=['KINETIC ENERGY','ROTATION ENERGY','INTERNAL ENERGY','HOURGLASS ENERGY','SPRING ENERGY','ELASTIC CONTACT ENERGY','FRICTIONAL CONTACT ENERGY','DAMPING CONTACT ENERGY '];E=sum(H[k] for k in terms)*.001;R=E-E[0]-H['EXTERNAL WORK']*.001;G=sum(H[k] for k in terms if k!='KINETIC ENERGY')*.001;return R,G,E

def main():
    hguard();assert PROTOCOL.exists();assert not (D/'review.json').exists();a=read(HC)['acceptance'];m=read(D/'mesh.json');g=read(D/'generation.json');H=histories(D/(N+'T01.csv'));Ho=histories(D/'observer'/(N+'T02_recovered.csv'));C={k:np.r_[v,Ho[k][0]] for k,v in H.items()};native=np.load(D/'native_global_history.npz');B=dict(zip(native['columns'].tolist(),native['values'].T));T=B['time'];R,G,E=ledger(B);RCsv,GCsv,ECsv=ledger(C)
    active=G>a['local_energy_comparison_minimum_J'];excess=abs(R)-a['local_energy_residual_generated_energy_fraction']*G-a['CSV_KE_precision_allowance_J'];bad=active&(excess>0);windows=[]
    for lo,hi in read(PROTOCOL)['windows_ms']:
        mask=(T>=lo)&(T<=hi);ix=np.flatnonzero(mask);worst=ix[np.argmax(excess[mask])];windows.append({'window_ms':[lo,hi],'native_failed_rows':int(bad[mask].sum()),'first_failure_ms':float(T[np.flatnonzero(mask&bad)[0]]) if (mask&bad).any() else None,'maximum_gate_excess_J':float(excess[worst]),'worst_time_ms':float(T[worst]),'residual_at_worst_J':float(R[worst]),'generated_at_worst_J':float(G[worst])})
    contact=segments(H);J=sum(contact.values());J-=J[0];P=np.column_stack([H[z+'-MOMENTUM'] for z in 'XYZ'])*.001;Pf=np.column_stack([sum((H[k] for k in H if k.startswith('FACADE_') and k.strip().endswith(z+'MOM')),np.zeros(len(H['time']))) for z in 'XYZ'])*.001;Js=np.column_stack([sum((H[k] for k in H if k.startswith('SUPPORT_IMPULSE_'+z)),np.zeros(len(H['time']))) for z in 'XYZ'])*.001;Js-=Js[0];jmax=float(np.linalg.norm(J,axis=1).max());mtol=a['momentum_absolute_allowance_Ns']+a['momentum_relative_allowance']*jmax;ge=float(np.linalg.norm(P-P[0]-Js,axis=1).max());fe=float(np.linalg.norm(Pf-Pf[0]-J-Js,axis=1).max())
    OLD=histories(SOURCE/'A20_CORE3D_TIED_20T01.csv');OJ=sum(segments(OLD).values());OJ-=OJ[0];oldraw=np.load(OUT/'native_global_energy_SI.npz');oldG=np.interp(T,oldraw['time_ms'],oldraw['generated_energy_J']);oldR=np.interp(T,oldraw['time_ms'],oldraw['residual_J']);oj=np.column_stack([np.interp(H['time'],OLD['time'],OJ[:,j]) for j in range(3)]);jerr=np.linalg.norm(J-oj,axis=1);common_t=float(H['time'][-1]);old_end_j=oj[-1];new_end_j=J[-1];old_end_g=float(oldG[-1]);relj=float(np.linalg.norm(new_end_j-old_end_j))/max(float(np.linalg.norm(old_end_j)),1e-30);relg=abs(float(G[-1])-old_end_g)/max(abs(old_end_g),1e-30)
    comparisons={'common_last_main_history_ms':common_t,'comparison_native_end_ms':float(T[-1]),'old_impulse_Ns':old_end_j.tolist(),'new_impulse_Ns':new_end_j.tolist(),'end_impulse_relative_difference':relj,'maximum_history_impulse_difference_Ns':float(jerr.max()),'maximum_impulse_norm_reference_Ns':float(np.linalg.norm(oj,axis=1).max()),'old_generated_end_interpolated_J':old_end_g,'new_generated_end_J':float(G[-1]),'end_generated_relative_difference':relg,'maximum_generated_history_difference_J':float(abs(G-oldG).max()),'end_impulse_halfdt_gate':relj<a['half_dt_impulse_difference_fraction'],'end_generated_halfdt_gate':relg<a['half_dt_generated_energy_difference_fraction'],'old_solver_rerun':False,'only_engine_time_step_changed':True}
    animations=sorted(p for p in D.glob(N+'A*') if re.fullmatch(re.escape(N)+r'A\d{3}',p.name))+sorted(p for p in (D/'observer').glob(N+'A*') if re.fullmatch(re.escape(N)+r'A\d{3}',p.name));skinids=[r['id'] for r in m['radome_skin_quads']];coreids=[r[0] for r in m['radome_core_bricks']];cohids=[s['element_id'] for s in m['cohesive_seams']];minIE=0.;skinrows=[];frametimes=[]
    for p in animations:
        z=fast(p);ix={int(e):j for j,e in enumerate(z['eid'])};si=np.array([ix[e] for e in skinids]);ie=z['scalar']['Specific Energy'][si]*z['element_mass_g'][si]*.001;minimum=float(ie.min(initial=0));minIE=min(minIE,minimum);frametimes.append(z['time_ms']);skinrows.append({'time_ms':z['time_ms'],'minimum_skin_element_IE_J':minimum,'negative_skin_elements':int((ie<-.001).sum()),'skin_IE_sum_J':float(ie.sum())})
    sel=sorted({int(np.argmin(abs(np.asarray(frametimes)-target))) for target in read(PROTOCOL)['geometry_sample_target_ms']});states=[];poses=[];vels=[];times=[];SA=[];CA=[];EA=[];maxmetal=0.;maxfacade=0.;supporterr=0.;mincore=0.;x0=np.asarray(m['nodes_mm']);fixed=np.array(m['fixed_node_ids'])-1;finite=True;topcheck=True
    for idx in sel:
        p=animations[idx];z=fast(p);q=vtk(subprocess.run([str(RUNTIME/'anim_to_vtk_win64.exe'),str(p)],capture_output=True,text=True,check=True,timeout=120).stdout);order=np.argsort(q['NODE_ID']);zo=np.argsort(z['nid']);assert np.array_equal(q['NODE_ID'][order],np.arange(1,len(x0)+1)) and np.array_equal(z['nid'][zo],np.arange(1,len(x0)+1));X=z['x'][zo];V=z['vector']['Velocity'][zo];U=q['Displacement'].reshape(-1,3)[order];assert np.allclose(X,q['points'].reshape(-1,3)[order],rtol=5e-6,atol=1e-6) and np.allclose(V,q['Velocity'].reshape(-1,3)[order],rtol=5e-6,atol=1e-6);supporterr=max(supporterr,float(abs(U[fixed]).max()));finite=finite and bool(all(np.isfinite(v).all() for v in [X,V,U]));ei={int(e):j for j,e in enumerate(q['ELEMENT_ID']) if e>0};si=np.array([ei[e] for e in skinids]);ci=np.array([ei[e] for e in coreids]);co=np.array([ei[e] for e in cohids]);eps=np.vstack([q[k] for k in q if 'Plast_Strn_Layer_' in k]).max(axis=0);metal=q['types']==5;facade=q['types']==9;maxmetal=max(maxmetal,float(eps[metal].max(initial=0)));maxfacade=max(maxfacade,float(eps[facade].max(initial=0)));cells=topology(q)
        for e,nodes in zip(m['aircraft_triangle_ids'],m['original_triangle_node_ids']):topcheck=topcheck and cells[ei[e]][:3]==nodes
        topcheck=topcheck and all(cells[ei[r['id']]]==r['nodes'] for r in m['radome_skin_quads']) and all(cells[ei[r[0]]]==r[1:] for r in m['radome_core_bricks']+m['cohesive_connectivity']);cm=np.array([f['core_volume_mm3']*4.8e-5/3 for f in m['radome_facets'] for j in range(3)]);coreE=q['3DELEM_Specific_Energy'][ci]*cm*.001;mincore=min(mincore,float(coreE.min(initial=0)))
        skinAlive=q['EROSION_STATUS'][si].astype(int);coreAlive=q['EROSION_STATUS'][ci].astype(int);cohAlive=q['EROSION_STATUS'][co].astype(int);times.append(z['time_ms']);poses.append(X.astype(np.float32)*.001);vels.append(V.astype(np.float32));SA.append(skinAlive);CA.append(coreAlive);EA.append(cohAlive);states.append({'path':rel(p),'time_ms':z['time_ms'],'native_binary_VTK_coordinates_and_velocity_agree':True,'deleted_skins':int((skinAlive==0).sum()),'deleted_core':int((coreAlive==0).sum()),'deleted_cohesive':int((cohAlive==0).sum()),'maximum_metal_plastic_strain':float(eps[metal].max(initial=0)),'maximum_facade_plastic_strain':float(eps[facade].max(initial=0)),'core_element_IE_sum_J':float(coreE.sum())});print(states[-1],flush=True)
    bk=[k for k in H if k.startswith('FORWARD_BEAM_DIAGNOSTIC')];beps=float(np.column_stack([H[k] for k in bk]).reshape(len(H['time']),len(g['beam_history_ids']),9)[:,:,8].max());mass=read(D/'starter_gate.json')['mass_CG'][0]*.001;step=float(B['TIME STEP'][-1]);iec=sum(C[k] for k in C if k.startswith('RADOME_CORE_FACET_') and k.strip().endswith(' IE'))*.001;ies=sum(C[k] for k in C if k.startswith(('RADOME_LOWER_FACET_','RADOME_UPPER_FACET_')) and k.strip().endswith(' IE'))*.001
    checks={'native_binary_CSV':read(D/'history_recovery.json')['pass'],'native_normal_termination':'NORMAL TERMINATION' in (D/'engine.log').read_text(),'requested_12ms_horizon':float(T[-1])>=12 and float(T[-1])-12<=a['final_timestamp_overshoot_native_step_factor']*step,'native_physical_mass':abs(mass-m['expected_total_mass_kg'])/mass<a['mass_relative_error'],'no_scaled_or_added_mass':bool(abs(B['ADDED MASS']).max()/(mass*1000)<a['added_mass_fraction']),'identical_A20_Starter_mechanics':read(D/'scene_audit.json')['pass'],'identical_A20_mass_CG_inertia':read(D/'starter_gate.json')['checks']['physical_mass_and_CG_identical'] and read(D/'starter_gate.json')['checks']['physical_inertia_identical'],'strict_zero_warnings':read(D/'starter_gate.json')['strict_zero_warning_pass'],'no_external_work':bool(np.all(B['EXTERNAL WORK']==0)),'global_energy':float(abs(R).max())/float(E[0])<a['global_energy_residual_initial_KE_fraction'],'native_local_energy':bool(active.any() and not bad.any()),'printed_CSV_local_energy':bool(np.all(abs(RCsv[active])<=a['local_energy_residual_generated_energy_fraction']*GCsv[active]+a['CSV_KE_precision_allowance_J'])),'global_support_momentum':ge<=mtol,'facade_contact_momentum':fe<=mtol,'halfdt_end_impulse':comparisons['end_impulse_halfdt_gate'],'halfdt_end_generated':comparisons['end_generated_halfdt_gate'],'sampled_native_geometry_finite':finite,'sampled_connectivity':topcheck,'supports_fixed':supporterr<1e-8,'metal_material_domain':maxmetal<=a['metal_plastic_strain_diagnostic_limit'],'facade_material_domain':maxfacade<=a['metal_plastic_strain_diagnostic_limit'],'beam_material_domain':beps<=a['metal_plastic_strain_diagnostic_limit'],'saved_skin_elements_IE_nonnegative':minIE>=-.001,'sampled_core_elements_IE_nonnegative':mincore>=-.001}
    checks={k:bool(x) for k,x in checks.items()};r={'created_utc':now(),'iteration':'AIRCRAFT-A21','case':N,'end_ms':float(T[-1]),'main_engine_seconds':read(D/'engine.log.execution.json')['seconds'],'mass_kg':mass,'initial_native_KE_J':float(E[0]),'final_native_residual_J':float(R[-1]),'final_native_generated_J':float(G[-1]),'maximum_native_residual_J':float(abs(R).max()),'native_failed_local_rows':int(bad.sum()),'maximum_native_CSV_residual_difference_J':float(abs(R-RCsv).max()),'windows':windows,'comparison':comparisons,'global_support_momentum_error_Ns':ge,'facade_contact_momentum_error_Ns':fe,'momentum_tolerance_Ns':mtol,'minimum_saved_skin_element_IE_J':minIE,'minimum_sampled_core_element_IE_J':mincore,'maximum_metal_plastic_strain':maxmetal,'maximum_facade_plastic_strain':maxfacade,'maximum_beam_plastic_strain':beps,'final_core_IE_J':float(iec[-1]),'final_skins_IE_J':float(ies[-1]),'native_geometry_states':states,'checks':checks,'failed_checks':[k for k,v in checks.items() if not v],'all_declared_checks_pass':all(checks.values()),'specific_whole_energy_cause_proven':False,'physical_impact_qualified':False,'seconds_extension_allowed':False,'objective1_complete':False,'no_inferred_RKE_or_balance_correction':True,'metal_fracture_modelled':False,'old_A20_preserved_and_not_rerun':True}
    np.savez_compressed(D/'balance_history_SI.npz',time_s=T*.001,residual_J=R,generated_energy_J=G,old_A20_residual_J=oldR,old_A20_generated_J=oldG,core_IE_J=iec,skin_IE_J=ies);np.savez_compressed(D/'verified_states_SI.npz',time_s=np.asarray(times)*.001,node_ids=np.arange(1,len(x0)+1),positions_m=np.asarray(poses),velocity_m_s=np.asarray(vels),skin_element_ids=skinids,skin_alive=np.asarray(SA),core_element_ids=coreids,core_alive=np.asarray(CA),cohesive_element_ids=cohids,cohesive_alive=np.asarray(EA));dump(D/'every_saved_skin_energy.json',{'frames':skinrows});dump(D/'review.json',r);print({k:r[k] for k in ['end_ms','failed_checks','windows','comparison','final_native_residual_J']},flush=True)

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('action',choices=['declare','main']);globals()[p.parse_args().action]()
