"""Compact verified saved-result comparisons and independent quadrature."""
import numpy as np
from run_aircraft_a06 import ROOT,OUT,CFG,PREV,read,dump,sha,rel,now,harness,preserved
def compare(pa,pb,label,jlim,elim):
    z0=np.load(pa/'balance_history_SI.npz');z1=np.load(pb/'balance_history_SI.npz');t=min(z0['time_s'][-1],z1['time_s'][-1]);js=[np.array([np.interp(t,z['time_s'],z['contact_impulse_Ns'][:,i]) for i in range(3)]) for z in [z0,z1]];es=[float(np.interp(t,z['time_s'],z['generated_energy_J'])) for z in [z0,z1]];re=[float(np.interp(t,z['time_s'],z['energy_residual_J'])) for z in [z0,z1]];dj=float(np.linalg.norm(js[1]-js[0])/np.linalg.norm(js[0]));de=abs(es[1]-es[0])/es[0]
    return {'comparison':label,'common_time_ms':float(t*1000),'impulse_relative_difference':dj,'generated_energy_relative_difference':de,'energy_residual_J':re,'impulse_pass':dj<=jlim,'energy_pass':de<=elim,'old_solver_rerun':False}
def main():
    dst=OUT/'summary.json';assert not dst.exists();c=read(CFG);a=c['acceptance'];paths={case['id']:OUT/'r1'/case['id'] for case in c['whole_aircraft']['cases']};rows=[read(d/'review.json') for d in paths.values()];sel=read(PREV/'case_selection.json')['case_directories']
    comparisons=[compare(paths['ZERO_DM'],paths['ZERO_DM_HALF'],'half_dt',a['half_dt_impulse_fraction'],a['half_dt_generated_energy_fraction']),compare(paths['ZERO_DM'],paths['ZERO_DM_FINE'],'spatial_mesh',a['mesh_impulse_fraction'],a['mesh_generated_energy_fraction']),compare(paths['ZERO_DM'],paths['ZERO_DM_TRUE_GAP'],'contact_gap_sensitivity',.1,.1),compare(PREV/sel['COMP_SELF'],paths['ZERO_DM'],'A05_default_vs_explicit_negligible_viscosity',.1,.1)]
    check=[]
    for d,r in zip(paths.values(),rows):
        z=np.load(d/'verified_states_SI.npz');b=np.load(d/'balance_history_SI.npz');m=read(d/'mesh.json');g=read(d/'generation.json');assert all(np.all(np.isfinite(z[k])) for k in z.files) and all(np.all(np.isfinite(b[k])) for k in b.files);assert len(z['node_ids'])==len(m['nodes_mm']);assert r['core_execution_and_transfer_checks_pass'];assert sha(d/'audit.json')==r['first_audit_sha256']
        check.append({'case':r['case']['id'],'states_sha256':sha(d/'verified_states_SI.npz'),'balances_sha256':sha(d/'balance_history_SI.npz'),'mass_kg':r['native_total_mass_kg'],'metadata_generator_snapshot_match':sha(OUT/'r1/generator_snapshot.py')==g['generator_sha256']})
    assert all(r['metadata_generator_snapshot_match'] for r in check)
    mono=read(OUT/'monotone_review.json');gq=[];xx,ww=np.polynomial.legendre.leggauss(8)
    for r in mono['cases']:
        le=r['candidate_Le_mm'];s=450.;E=22000.;G=50.;e0=s/E;ef=e0+2*G/(le*s);a0=le*s/(2*G)
        f=lambda e:E*e*(1-a0*(e-e0));e=(ef+e0)/2+(ef-e0)/2*xx;post=le*(ef-e0)/2*np.dot(ww,f(e));total=le*s*s/(2*E)+post;err=abs(total-r['initial_volume_analytic_G_total_N_mm'])/total;assert err<1e-12
        gq.append({'case':r['case']['id'],'Gauss8_total_N_mm':float(total),'closed_formula_relative_difference':float(err),'not_native_energy_validation':True})
    cy=read(OUT/'witness_review.json');reload=[]
    for r in cy['cases']:
        z=np.load(OUT/'w0'/r['case']['id']/'saved_witness_SI.npz');d=z['damage'];mon=bool(np.all(np.diff(d,axis=0)>=-1e-6));r0=np.array(r['face_damage_at_load_unload_reload'][0]);r2=np.array(r['face_damage_at_load_unload_reload'][2]);reload.append({'case':r['case']['id'],'damage_never_decreases_in_saved_states':mon,'damage_growth_at_same_0p04_strain_peak':float(np.max(r2-r0)),'not_a_new_higher_peak':True})
    proof=read(OUT/'source_manifest.json');assert all(sha(ROOT/r['path'])==r['sha256'] for r in proof['local_inputs'])
    dump(OUT/'source_transcription.json',{'created_utc':now(),'inherited_strengths':'HexPly913 face reference450/460MPa, not actual767 identification; 100MPa in-plane shear own hypothesis, short-beam65MPa not transferred','G_N_mm':50,'G_kJ_m2':50,'G_measured':False,'manual_vs_code':'Manual linear damage equation omits sigma/2 factor; pinned shell routine lines143-146 uses Le*d_epsilon*sigma_crit/(2G). Native simple slope reproduces it. Installed binary exact source commit not established.','native_output':'Damaged witness stress animation reports effective material stress; reaction impulse derivative and work reveal reduced resisting force. Do not use animation tensor as damaged force stress.','c_source_acquisition':{'url':c['sources'][3].replace('https://github.com/','https://raw.githubusercontent.com/').replace('/blob/','/'),'local':rel(ROOT/'wtc1_simulation_v8/input/aircraft_a06_sources/fail_orthenerg_c.F'),'sha256':sha(ROOT/'wtc1_simulation_v8/input/aircraft_a06_sources/fail_orthenerg_c.F')},'archive_read_count_this_iteration':0,'official_event_damage_as_target':False})
    dump(OUT/'tooling_attempts.json',{'r0':'Whole generation stopped on TYPE1 field-line indexing assertion, before native Starter/Engine; source snapshot and empty attempt retained. r1 edits line3, verified by native listing.','m0':'Supplementary generation stopped because hash helper expected Path, before Starter/Engine; source snapshot and generated inputs retained. m1 corrects Path only and builds new intact cases.','review_helpers':'Initial review dimensional diff-axis and NumPy boolean JSON errors repaired before final review; all native calculations preserved, no solver reruns.','old_native_solver_reruns':0,'native_T02_converter':'No repeated known A05 crash; validate every T01 binary frame against working native CSV, then decode single observer initial row.'})
    integrity=all(r['core_execution_and_transfer_checks_pass'] for r in rows) and mono['checks']['native_execution_and_energy_integrity'];hv=harness();n=preserved()
    summary={'created_utc':now(),'cases':rows,'comparisons':comparisons,'saved_array_review':check,'independent_reference_quadrature':gq,'cyclic_damage_diagnostics':reload,'integrity_only_pass':bool(integrity),'all_declared_checks_pass':False,'physical_impact_qualified':False,'fracture_energy_qualified':False,'failure_transfer_enabled':False,'local_energy_ledger_fully_qualified':all(r['checks']['energy_local_within_declared_limit'] for r in rows),'spatial_convergence_qualified':comparisons[1]['impulse_pass'] and comparisons[1]['energy_pass'],'historical_radome_reconstructed':False,'whole_aircraft_cases':4,'constitutive_witness_cases':8,'main_solver_jobs':12,'observation_jobs':4,'starter_jobs':12,'old_solver_reruns':0,'old_files_preserved':n,'harness':hv,'NIST_outcomes_used_as_target':False}
    assert integrity and n==3431;dump(dst,summary);print({'integrity_only':integrity,'comparisons':comparisons,'witness_irreversibility':reload,'all_gates_pass':False},flush=True)
if __name__=='__main__':main()
